name: realestate
description: "This apps for real estate."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  pdf: ^3.11.0
  printing: ^5.10.3
  device_preview: ^1.1.0
  shared_preferences: ^2.1.1
  google_fonts: ^6.1.0
  intl: ^0.20.2
  dropdown_search: ^5.0.3
  flutter_spinkit: ^5.1.0
  url_launcher: ^6.1.10
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/real_estate.jpg
    - assets/icons/
